/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.CourseResultJFrame;

import BLL.PersonBLL;
import BLL.StudentGradeBLL;
import DTO.PersonDTO;
import DTO.StudentGradeDTO;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author domin
 */
public class JFrameAddNewStudent extends javax.swing.JFrame {

    int courseID;
    PersonBLL personBll = new PersonBLL();
    StudentGradeBLL studentGradeBll = new StudentGradeBLL();
    
    
    public JFrameAddNewStudent(int courseID) {
        initComponents();
        this.courseID = courseID;
        enrollmentDateTxt.setText(getCurrentDate());
    }
    
    public static Timestamp convertStringToTimestamp(String dateString) {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date parsedDate = dateFormat.parse(dateString);
            return new Timestamp(parsedDate.getTime());
        } 
        catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public static String getCurrentDate() {
        Date currentDate = new Date();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        return dateFormat.format(currentDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        courseName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        closeFrameBtn = new javax.swing.JButton();
        addCourseBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        enrollmentDateTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel2.setText("Khóa học:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel2.setPreferredSize(new java.awt.Dimension(63, 40));

        courseName.setText("Tên khóa học mới");
        courseName.setPreferredSize(new java.awt.Dimension(220, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM MỚI HỌC SINH VÀO KHÓA HỌC");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel.setText("Last Name:");
        jLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel.setPreferredSize(new java.awt.Dimension(63, 40));

        lastNameTxt.setPreferredSize(new java.awt.Dimension(220, 40));

        jLabel3.setText("First Name:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(63, 40));

        firstNameTxt.setPreferredSize(new java.awt.Dimension(220, 40));

        closeFrameBtn.setBackground(new java.awt.Color(128, 128, 128));
        closeFrameBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeFrameBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeFrameBtn.setText("Đóng");
        closeFrameBtn.setBorder(null);
        closeFrameBtn.setPreferredSize(new java.awt.Dimension(75, 38));
        closeFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFrameBtnActionPerformed(evt);
            }
        });

        addCourseBtn.setText("Thêm");
        addCourseBtn.setBackground(new java.awt.Color(101, 183, 65));
        addCourseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 242, 176)));
        addCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCourseBtn.setPreferredSize(new java.awt.Dimension(75, 38));
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Enrollment Date:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(63, 40));

        enrollmentDateTxt.setEditable(false);
        enrollmentDateTxt.setPreferredSize(new java.awt.Dimension(220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrollmentDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enrollmentDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFrameBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeFrameBtnActionPerformed

    private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed
        String lastName = this.lastNameTxt.getText();
        String firstName = this.firstNameTxt.getText();
        Timestamp enrollmentDate = convertStringToTimestamp(enrollmentDateTxt.getText());
        
        if(lastName.isEmpty() || firstName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There is empty data field");
        }
        else {
            int id = personBll.getAutoIncrement();
            
            PersonDTO person = new PersonDTO();
            person.setPersonID(id);
            person.setLastName(lastName);
            person.setFirstName(firstName);
            person.setEnrollmentDate(enrollmentDate);
            personBll.insertPerson(person);
            
            StudentGradeDTO studentGrade = new StudentGradeDTO();
            studentGrade.setCourseID(courseID);
            studentGrade.setStudentID(id);
            studentGrade.setGrade(null);
            studentGradeBll.insertStudent(studentGrade);
            
            JOptionPane.showMessageDialog(null, "Add success");
            clearInput();
        }
    }//GEN-LAST:event_addCourseBtnActionPerformed

    public void clearInput() {
        this.lastNameTxt.setText("");
        this.firstNameTxt.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseBtn;
    private javax.swing.JButton closeFrameBtn;
    private javax.swing.JTextField courseName;
    private javax.swing.JTextField enrollmentDateTxt;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastNameTxt;
    // End of variables declaration//GEN-END:variables
}
