/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.CourseResultJFrame;

import javax.swing.DefaultComboBoxModel;
import BLL.CourseBLL;
import BLL.StudentGradeBLL;
import DTO.CourseDTO;
import DTO.StudentGradeDTO;
import javax.swing.JOptionPane;
/**
 *
 * @author MSI
 */
public class JFrameChangeCourse extends javax.swing.JFrame {
    CourseBLL courseBLL=new CourseBLL();
    StudentGradeBLL studentGradeBLL=new StudentGradeBLL();
    int courseID;
    double grade;
    /**
     * Creates new form JFrameChangeCourse
     */
    public JFrameChangeCourse(int PersonID,int CourseID,String name,String Course,double Grade) {
        initComponents();
        LoadData();
        courseID=CourseID;
        grade=Grade;
        jTextPersonID.setText(PersonID+"");
        jTextName.setText(name);
        jTextCourseCurrentID.setText(Course);
   }
    public void LoadData(){
        DefaultComboBoxModel model=new DefaultComboBoxModel<>();
        for(CourseDTO i:courseBLL.selectAllCourse()){
            model.addElement(i.getCourseID()+"-"+i.getTitle());
        }
        jComboBoxCourse.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCourseCurrentID = new javax.swing.JTextField();
        jTextPersonID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PersonID");

        jLabel2.setText("Name");

        jTextCourseCurrentID.setEnabled(false);

        jTextPersonID.setEnabled(false);

        jLabel3.setText("Current course");

        jTextName.setEnabled(false);

        jLabel4.setText("Course");

        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCourseCurrentID, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCourseCurrentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
StudentGradeDTO studentGradeDTO=new StudentGradeDTO();
        String tmp[]=jComboBoxCourse.getSelectedItem().toString().split("-");
        studentGradeDTO.setCourseID(Integer.parseInt(tmp[0]));
        studentGradeDTO.setGrade(0d);
        studentGradeDTO.setEnrollmentID(studentGradeBLL.getEnrollment(courseID,Integer.parseInt(jTextPersonID.getText().toString())));
        if(studentGradeBLL.getEnrollment(Integer.parseInt(tmp[0]),Integer.parseInt(jTextPersonID.getText().toString()))!=0){
            JOptionPane.showMessageDialog(rootPane,"students are studying the course");
        }
        else{
            int choice=0;
            if(grade!=0d){
                choice = JOptionPane.showConfirmDialog(rootPane, "Do You Want To Change Course?", "Confirm", JOptionPane.YES_NO_OPTION);
                System.out.println(choice);
                if(choice==JOptionPane.YES_OPTION){
                    if(studentGradeBLL.updateGrade(studentGradeDTO)){
                        JOptionPane.showMessageDialog(rootPane,"Change Course Success!");
                        this.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane,"Change Course Failed!");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Change Course Failed!");
                }
            }
            else{
                if(studentGradeBLL.updateGrade(studentGradeDTO)){
                    JOptionPane.showMessageDialog(rootPane,"Change Course Success!");
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Change Course Failed!");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextCourseCurrentID;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPersonID;
    // End of variables declaration//GEN-END:variables
}
