/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.CourseResultJFrame;

import BLL.PersonBLL;
import BLL.StudentGradeBLL;
import DTO.PersonDTO;
import DTO.StudentGradeDTO;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author domin
 */
public class JFrameListStudent extends javax.swing.JFrame {

    PersonBLL personBLL = new PersonBLL();
    StudentGradeBLL studentGradeBll = new StudentGradeBLL();
    int studentID, courseID;
    /**
     * Creates new form JFrameListStudent
     */
    public JFrameListStudent(int courseID, String Title) {
        initComponents();
        this.courseID = courseID;
        jButtonClearSearch.setVisible(false);
        jTitle.setText(courseID+" - "+Title);
        LoadData();
        jSearch.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
              SearchAll();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
              SearchAll();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
        // Xử lý khi có sự thay đổi trong thuộc tính của văn bản
        // (chẳng hạn như một loại thuộc tính được thay đổi, nhưng không phải nội dung văn bản)
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jTitle = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonClearSearch = new javax.swing.JButton();
        jSearch = new javax.swing.JTextField();
        searchOnsiteCourseBtn2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        closeFrameBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "PersonID", "FirstName", "LastName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStudent);

        jTitle.setText("Title");
        jTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonSave.setText("Thêm");
        jButtonSave.setBackground(new java.awt.Color(155, 207, 83));
        jButtonSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel7.setText("THÊM SINH VIÊN VÀO KHÓA HỌC");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jButtonClearSearch.setText("X");
        jButtonClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearSearchActionPerformed(evt);
            }
        });

        jSearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSearch.setPreferredSize(new java.awt.Dimension(300, 40));

        searchOnsiteCourseBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-search-24.png"))); // NOI18N
        searchOnsiteCourseBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchOnsiteCourseBtn2.setMargin(new java.awt.Insets(2, 20, 3, 0));
        searchOnsiteCourseBtn2.setPreferredSize(new java.awt.Dimension(40, 40));
        searchOnsiteCourseBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOnsiteCourseBtn2ActionPerformed(evt);
            }
        });

        closeFrameBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeFrameBtn.setText("Đóng");
        closeFrameBtn.setBorder(null);
        closeFrameBtn.setPreferredSize(new java.awt.Dimension(75, 38));
        closeFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFrameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchOnsiteCourseBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchOnsiteCourseBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonClearSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeFrameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentMouseClicked
        // TODO add your handling code here:
        int n = jTableStudent.getSelectedRow();
        studentID = Integer.parseInt(jTableStudent.getValueAt(n,1).toString());
    }//GEN-LAST:event_jTableStudentMouseClicked

    public void SearchTable(String text){
        DefaultTableModel faut = (DefaultTableModel) jTableStudent.getModel();
        TableRowSorter<DefaultTableModel> search = new TableRowSorter<>(faut);
        jTableStudent.setRowSorter(search);
        search.setRowFilter(RowFilter.regexFilter("(?i)"+text));
    }
    public void SearchAll(){
         if(jSearch.getText().isEmpty()){
            jButtonClearSearch.setVisible(false);
            jTableStudent.setRowSorter(null);
            LoadData();
        }else{
            SearchTable(jSearch.getText().toString());
            jButtonClearSearch.setVisible(true);
        }
    }
    
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        if(studentGradeBll.getEnrollment(courseID, studentID) == 0) {
            JOptionPane.showMessageDialog(null, "Add success");
            
            StudentGradeDTO studentGrade = new StudentGradeDTO();
            studentGrade.setCourseID(courseID);
            studentGrade.setStudentID(studentID);
            studentGrade.setGrade(0);
            
            studentGradeBll.insertStudent(studentGrade);
        }
        else {
            JOptionPane.showMessageDialog(null, "This student is already in the classroom");
        }
        jTableStudent.clearSelection();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearSearchActionPerformed
        // TODO add your handling code here:
        jSearch.setText("");
        LoadData();
    }//GEN-LAST:event_jButtonClearSearchActionPerformed

    private void searchOnsiteCourseBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOnsiteCourseBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchOnsiteCourseBtn2ActionPerformed

    private void closeFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFrameBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeFrameBtnActionPerformed

    public void LoadData(){
        String columns[]=new String[]{"STT","PersonID","FirstName","LastName"};
        DefaultTableModel model=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for(String i:columns){
            model.addColumn(i);
        }
        int stt=0;
        for(PersonDTO i : personBLL.getListStudent()){
           Vector t=new Vector();
           t.add(stt+=1);
           t.add(i.getPersonID());
           t.add(i.getFirstName());
           t.add(i.getLastName());
           model.addRow(t);
        }
        jTableStudent.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeFrameBtn;
    private javax.swing.JButton jButtonClearSearch;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearch;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JLabel jTitle;
    private javax.swing.JButton searchOnsiteCourseBtn2;
    // End of variables declaration//GEN-END:variables
}
