/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UI.MemberManagement.MemberPanel;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private final Color darkGreen = new Color(0, 143, 143);
    private final ArrayList<JButton> allBtnLeftBar = new ArrayList<>();
    private final ArrayList<JButton> allBtnLeftSubBar = new ArrayList<>();
    private final MemberPanel memberPanel = new MemberPanel();
    private boolean dropdownToggle = false;
    private final int heightBar = 150;

    public Home() {
        initComponents();
        allBtnLeftBar.addAll(Arrays.asList(memberBtn, deviceBtn, punishBtn, memberStatBtn, deviceStatBtn, punishStatBtn));
        switchPanel(memberPanel, memberBtn);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        memberBtn = new javax.swing.JButton();
        deviceBtn = new javax.swing.JButton();
        punishBtn = new javax.swing.JButton();
        statisticsBtn = new javax.swing.JButton();
        subBarStat = new javax.swing.JPanel();
        memberStatBtn = new javax.swing.JButton();
        deviceStatBtn = new javax.swing.JButton();
        punishStatBtn = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        devicePnl = new javax.swing.JPanel();
        punishPnl = new javax.swing.JPanel();
        memberStatPnl = new javax.swing.JPanel();
        deviceStatPnl = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        container.setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(255, 255, 255));
        sideBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        sideBar.setPreferredSize(new java.awt.Dimension(220, 693));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        sideBar.setLayout(flowLayout1);

        memberBtn.setText("Member Management");
        memberBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        memberBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        memberBtn.setOpaque(true);
        memberBtn.setPreferredSize(new java.awt.Dimension(219, 50));
        memberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberBtnActionPerformed(evt);
            }
        });
        sideBar.add(memberBtn);

        deviceBtn.setText("Device Management");
        deviceBtn.setToolTipText("");
        deviceBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        deviceBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deviceBtn.setIconTextGap(12);
        deviceBtn.setOpaque(true);
        deviceBtn.setPreferredSize(new java.awt.Dimension(219, 50));
        deviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceBtnActionPerformed(evt);
            }
        });
        sideBar.add(deviceBtn);

        punishBtn.setText("Punish Management");
        punishBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        punishBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        punishBtn.setOpaque(true);
        punishBtn.setPreferredSize(new java.awt.Dimension(219, 50));
        punishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishBtnActionPerformed(evt);
            }
        });
        sideBar.add(punishBtn);

        statisticsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-arrow-down-20.png"))); // NOI18N
        statisticsBtn.setText("Statistics Management");
        statisticsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        statisticsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statisticsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        statisticsBtn.setIconTextGap(50);
        statisticsBtn.setOpaque(true);
        statisticsBtn.setPreferredSize(new java.awt.Dimension(219, 50));
        statisticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsBtnActionPerformed(evt);
            }
        });
        sideBar.add(statisticsBtn);

        subBarStat.setBackground(new java.awt.Color(255, 255, 255));
        subBarStat.setPreferredSize(new java.awt.Dimension(219, 150));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        subBarStat.setLayout(flowLayout2);

        memberStatBtn.setBackground(new java.awt.Color(226, 226, 226));
        memberStatBtn.setText("Member");
        memberStatBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 0));
        memberStatBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        memberStatBtn.setPreferredSize(new java.awt.Dimension(219, 50));
        subBarStat.add(memberStatBtn);

        deviceStatBtn.setBackground(new java.awt.Color(226, 226, 226));
        deviceStatBtn.setText("Device");
        deviceStatBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 0));
        deviceStatBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deviceStatBtn.setPreferredSize(new java.awt.Dimension(219, 50));
        subBarStat.add(deviceStatBtn);

        punishStatBtn.setBackground(new java.awt.Color(226, 226, 226));
        punishStatBtn.setText("Punish");
        punishStatBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 0));
        punishStatBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        punishStatBtn.setPreferredSize(new java.awt.Dimension(219, 50));
        subBarStat.add(punishStatBtn);

        sideBar.add(subBarStat);

        cardPanel.setLayout(new java.awt.CardLayout());

        devicePnl.setBackground(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout devicePnlLayout = new javax.swing.GroupLayout(devicePnl);
        devicePnl.setLayout(devicePnlLayout);
        devicePnlLayout.setHorizontalGroup(
            devicePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        devicePnlLayout.setVerticalGroup(
            devicePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        cardPanel.add(devicePnl, "card3");

        punishPnl.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout punishPnlLayout = new javax.swing.GroupLayout(punishPnl);
        punishPnl.setLayout(punishPnlLayout);
        punishPnlLayout.setHorizontalGroup(
            punishPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        punishPnlLayout.setVerticalGroup(
            punishPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        cardPanel.add(punishPnl, "card4");

        memberStatPnl.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout memberStatPnlLayout = new javax.swing.GroupLayout(memberStatPnl);
        memberStatPnl.setLayout(memberStatPnlLayout);
        memberStatPnlLayout.setHorizontalGroup(
            memberStatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        memberStatPnlLayout.setVerticalGroup(
            memberStatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        cardPanel.add(memberStatPnl, "card5");

        deviceStatPnl.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout deviceStatPnlLayout = new javax.swing.GroupLayout(deviceStatPnl);
        deviceStatPnl.setLayout(deviceStatPnlLayout);
        deviceStatPnlLayout.setHorizontalGroup(
            deviceStatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        deviceStatPnlLayout.setVerticalGroup(
            deviceStatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        cardPanel.add(deviceStatPnl, "card6");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceBtnActionPerformed
        switchPanel(devicePnl, deviceBtn);

    }//GEN-LAST:event_deviceBtnActionPerformed

    private void statisticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsBtnActionPerformed
        toggleDropdown();
    }//GEN-LAST:event_statisticsBtnActionPerformed

    private void memberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberBtnActionPerformed
        switchPanel(memberPanel, memberBtn);

    }//GEN-LAST:event_memberBtnActionPerformed

    private void punishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishBtnActionPerformed
        switchPanel(punishPnl, punishBtn);
    }//GEN-LAST:event_punishBtnActionPerformed
    public void setBackgroundDefaultAllButton() {
        for (JButton btn : allBtnLeftBar) {
            btn.setBackground(Color.WHITE);
            btn.setForeground(Color.BLACK);
        }
        for (JButton btn : allBtnLeftSubBar) {
            btn.setBackground(Color.BLACK);
            btn.setForeground(Color.BLACK);
        }
    }

    private void switchPanel(Component panel, JButton btn) {
        cardPanel.removeAll();
        cardPanel.add(panel);
        cardPanel.repaint();
        cardPanel.revalidate();
        setBackgroundDefaultAllButton();
        btn.setBackground(darkGreen);
        btn.setForeground(Color.WHITE);
        dropdownToggle = false;
        closeMenu();

    }

    private void toggleDropdown() {
        dropdownToggle = !dropdownToggle;
        if (dropdownToggle) {
            statisticsBtn.setIcon(new ImageIcon(getClass().getResource("/images/icons8-arrow-up-20.png")));
            openMenu();
        } else {
            statisticsBtn.setIcon(new ImageIcon(getClass().getResource("/images/icons8-arrow-down-20.png")));
            closeMenu();
        }
    }

    public void openMenu() {
        int initialHeight = subBarStat.getPreferredSize().height;
        int steps = 100 / 10; // 10 ms interval between each step
        int stepHeight = heightBar / steps;

        Timer timer = new Timer(10, new ActionListener() {
            int currentHeight = initialHeight;

            @Override
            public void actionPerformed(ActionEvent e) {
                currentHeight += stepHeight;
                if (currentHeight >= heightBar) {
                    currentHeight = heightBar;
                    ((Timer) e.getSource()).stop();
                }
                Dimension newPreferredSize = new Dimension(220, currentHeight);
                subBarStat.setPreferredSize(newPreferredSize);
                subBarStat.revalidate();
            }
        });
        timer.start();
    }

    public void closeMenu() {
        int initialHeight = subBarStat.getPreferredSize().height;
        int steps = 100 / 10; // 10 ms interval between each step
        int stepHeight = initialHeight / steps;

        Timer timer = new Timer(10, new ActionListener() {
            int currentHeight = initialHeight;

            @Override
            public void actionPerformed(ActionEvent e) {
                currentHeight -= stepHeight;
                if (currentHeight <= 0) {
                    currentHeight = 0;
                    ((Timer) e.getSource()).stop();
                }
                Dimension newPreferredSize = new Dimension(220, currentHeight);
                subBarStat.setPreferredSize(newPreferredSize);
                subBarStat.revalidate();
            }
        });
        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel container;
    private javax.swing.JButton deviceBtn;
    private javax.swing.JPanel devicePnl;
    private javax.swing.JButton deviceStatBtn;
    private javax.swing.JPanel deviceStatPnl;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton memberBtn;
    private javax.swing.JButton memberStatBtn;
    private javax.swing.JPanel memberStatPnl;
    private javax.swing.JButton punishBtn;
    private javax.swing.JPanel punishPnl;
    private javax.swing.JButton punishStatBtn;
    private javax.swing.JPanel sideBar;
    private javax.swing.JButton statisticsBtn;
    private javax.swing.JPanel subBarStat;
    // End of variables declaration//GEN-END:variables
}
