/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.MemberManagement;

import BLL.DeviceBLL;
import BLL.UsageBLL;
import POJOs.Device;
import POJOs.Member;
import POJOs.Usage;
import Utils.sharedFunction;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class BorrowDeviceFrame extends javax.swing.JFrame {

    /**
     * Creates new form BorrowDevicePanel
     */
    private final UsageBLL usageBLL = new UsageBLL();
    private final DeviceBLL deviceBLL = new DeviceBLL();
    private final sharedFunction func = new sharedFunction();
    private Member currentMember;
    private List<Integer> usageIDList = new ArrayList<>();

    public BorrowDeviceFrame(Member member) {
        currentMember = member;
        initComponents();
        borrowingHistory();
    }

    public Member getCurrentMember() {
        return currentMember;
    }

    public void updateTable() {
        borrowingHistory();
    }

    private void borrowingHistory() {
        List<Usage> usageList = usageBLL.selectByMemberID(currentMember);
        DefaultTableModel model = (DefaultTableModel) tblBorrowedDevice.getModel();
        model.setRowCount(0);

        int STT = 1;
        for (Usage usage : usageList)
        {
            int usageID = usage.getId();
            usageIDList.add(usageID);
            Device device = usage.getDevice();
            int deviceID = device.getId();
            String deviceName = device.getName();
            Timestamp borrowedTime = usage.getBorrowedTime();
            Timestamp paidTime = usage.getPaidTime();
            
            Object[] row
                    =
                    {
                        STT++, deviceID, deviceName, borrowedTime, paidTime
                    };
            model.addRow(row);
        }
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        returnDeviceBtn = new javax.swing.JButton();
        borrowDeviceBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowedDevice = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List of borrowed devices");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("LIST OF BORROWED DEVICES");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout1);

        returnDeviceBtn.setBackground(new java.awt.Color(0, 143, 143));
        returnDeviceBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnDeviceBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnDeviceBtn.setText("- Return One");
        returnDeviceBtn.setBorder(null);
        returnDeviceBtn.setPreferredSize(new java.awt.Dimension(120, 40));
        returnDeviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDeviceBtnActionPerformed(evt);
            }
        });
        jPanel3.add(returnDeviceBtn);

        borrowDeviceBtn.setBackground(new java.awt.Color(0, 143, 143));
        borrowDeviceBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        borrowDeviceBtn.setForeground(new java.awt.Color(255, 255, 255));
        borrowDeviceBtn.setText("+ Borrow new");
        borrowDeviceBtn.setBorder(null);
        borrowDeviceBtn.setPreferredSize(new java.awt.Dimension(120, 40));
        borrowDeviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowDeviceBtnActionPerformed(evt);
            }
        });
        jPanel3.add(borrowDeviceBtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblBorrowedDevice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "ID", "Name", "Borrowing Time", "Return Time"
            }
        ));
        tblBorrowedDevice.setRowHeight(30);
        tblBorrowedDevice.setShowGrid(true);
        jScrollPane2.setViewportView(tblBorrowedDevice);
        if (tblBorrowedDevice.getColumnModel().getColumnCount() > 0) {
            tblBorrowedDevice.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblBorrowedDevice.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblBorrowedDevice.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblBorrowedDevice.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblBorrowedDevice.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void borrowDeviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowDeviceBtnActionPerformed
        // TODO add your handling code here:    
        BorrowNewDeviceFrame borrowNewDeviceFrame = new BorrowNewDeviceFrame(this);
        borrowNewDeviceFrame.setVisible(true);
    }//GEN-LAST:event_borrowDeviceBtnActionPerformed

    private void returnDeviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDeviceBtnActionPerformed
        // TODO add your handling code here:
        int row = tblBorrowedDevice.getSelectedRow();
        if (row == -1)
        {
            func.displayErrorMessage("Please choose a record!!");
        } else
        {
            Object valPaidTime = tblBorrowedDevice.getValueAt(row, 4);
            if (valPaidTime != null)
            {
                func.displayErrorMessage("The device has been returned");
            } else
            {
                Timestamp currentTimestamp = new Timestamp(System.currentTimeMillis());
                int STT = Integer.parseInt(tblBorrowedDevice.getValueAt(row, 0).toString());
                int currentIndex = STT  - 1;
                int usageID = usageIDList.get(currentIndex);
                Usage currentUsage = usageBLL.getById(usageID);
                currentUsage.setPaidTime(currentTimestamp);
                usageBLL.update(currentUsage);
                
                borrowingHistory();
                func.displayConfirmMessage("Device returned successfully!!");
            }
        }
    }//GEN-LAST:event_returnDeviceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BorrowDeviceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BorrowDeviceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BorrowDeviceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BorrowDeviceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new BorrowDeviceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowDeviceBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton returnDeviceBtn;
    private javax.swing.JTable tblBorrowedDevice;
    // End of variables declaration//GEN-END:variables
}
