/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MainPanel;

import BLL.CourseBLL;
import BLL.DepartmentBLL;
import BLL.OnlineCourseBLL;
import BLL.OnsiteCourseBLL;
import DTO.CourseDTO;
import DTO.DepartmentDTO;
import DTO.OnlineCourseDTO;
import DTO.OnsiteCourseDTO;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;
import java.time.LocalTime;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author ASUS
 */
public class CoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form CoursePanel
     */
    private final CourseAddForm courseAddForm = new CourseAddForm();
    private final CourseBLL courseBLL;
    private final OnlineCourseBLL onlineCourseBLL;
    private final OnsiteCourseBLL onsiteCourseBLL;
    private final DepartmentBLL departmentBLL;
    private List<CourseDTO> listCourse;
    private List<DepartmentDTO> listDepartment;
    private static DefaultTableModel modelCourse;

    public CoursePanel() {
        courseBLL = new CourseBLL();
        onlineCourseBLL = new OnlineCourseBLL();
        onsiteCourseBLL = new OnsiteCourseBLL();
        departmentBLL = new DepartmentBLL();
        initComponents();
        loadDepartmentName();
        loadData();
    }

    private void loadData() {
        listCourse = courseBLL.selectAllCourse();

         DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
         model.setRowCount(0);

        int STT = 1;
        for (CourseDTO course : listCourse)
        {
            int courseID = course.getCourseID();
            String title = course.getTitle();
            System.out.println(title);
            int credits = course.getCredits();
            int departmentID = course.getDepartmentID();
            String departmentName = departmentBLL.selectByID(departmentID).getName();
            String course_type = course.getCourse_type();

            Object[] row =
            {
                STT++, courseID, title, credits, departmentName, course_type
            };
            model.addRow(row);
        }
        model.fireTableDataChanged();
    }

    private void loadDepartmentName() {
        listDepartment = departmentBLL.selectAll();
        for (DepartmentDTO departmentDTO : listDepartment)
        {
            String name = departmentDTO.getName();
            cbDepartment.addItem(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortCourseBtnGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        addCourseBtn = new javax.swing.JButton();
        editCourseBtn = new javax.swing.JButton();
        deleteCourseBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        searchOnsiteCourseValue = new javax.swing.JTextField();
        searchOnsiteCourseBtn = new javax.swing.JButton();
        sortCourseBtnGroupPnl = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        detailCoursePanel = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCourseIDPnl = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        txtCourseNamePnl = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtDepartmentPnl = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        cbDepartment = new javax.swing.JComboBox<>();
        txtCreditPnl = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtCredit = new javax.swing.JTextField();
        txtDetailCourse = new javax.swing.JPanel();
        txtLocationPnl = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtUrlPnl = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        txtTimePnl = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tpTime = new com.github.lgooddatepicker.components.TimePicker();
        txtDatePnl = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        txtMonday = new javax.swing.JCheckBox();
        txtTuesday = new javax.swing.JCheckBox();
        txtWednesday = new javax.swing.JCheckBox();
        txtThursday = new javax.swing.JCheckBox();
        txtFriday = new javax.swing.JCheckBox();
        txtSaturday = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        buttonPnl = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("QUẢN LÝ KHÓA HỌC");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 206, 206)));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 62));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanel5.setLayout(flowLayout2);

        addCourseBtn.setText("Thêm");
        addCourseBtn.setBackground(new java.awt.Color(155, 207, 83));
        addCourseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 234, 124)));
        addCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCourseBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });
        jPanel5.add(addCourseBtn);

        editCourseBtn.setText("Sửa");
        editCourseBtn.setBackground(new java.awt.Color(64, 162, 227));
        editCourseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 226, 236)));
        editCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editCourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        editCourseBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        editCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseBtnActionPerformed(evt);
            }
        });
        jPanel5.add(editCourseBtn);

        deleteCourseBtn.setText("Xóa");
        deleteCourseBtn.setBackground(new java.awt.Color(255, 104, 104));
        deleteCourseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 128, 128)));
        deleteCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteCourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteCourseBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        deleteCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseBtnActionPerformed(evt);
            }
        });
        jPanel5.add(deleteCourseBtn);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(650, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout1);

        searchOnsiteCourseValue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        searchOnsiteCourseValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchOnsiteCourseValue.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.add(searchOnsiteCourseValue);

        searchOnsiteCourseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-search-24.png"))); // NOI18N
        searchOnsiteCourseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchOnsiteCourseBtn.setMargin(new java.awt.Insets(2, 20, 3, 0));
        searchOnsiteCourseBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        searchOnsiteCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOnsiteCourseBtnActionPerformed(evt);
            }
        });
        jPanel4.add(searchOnsiteCourseBtn);

        jPanel5.add(jPanel4);

        sortCourseBtnGroupPnl.setBackground(new java.awt.Color(255, 255, 255));
        sortCourseBtnGroupPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 206, 206)));
        sortCourseBtnGroupPnl.setPreferredSize(new java.awt.Dimension(310, 40));
        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout6.setAlignOnBaseline(true);
        sortCourseBtnGroupPnl.setLayout(flowLayout6);

        sortCourseBtnGroup.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Tất cả");
        jRadioButton1.setPreferredSize(new java.awt.Dimension(60, 30));
        sortCourseBtnGroupPnl.add(jRadioButton1);

        sortCourseBtnGroup.add(jRadioButton2);
        jRadioButton2.setText("Khóa học onsite");
        jRadioButton2.setPreferredSize(new java.awt.Dimension(108, 30));
        sortCourseBtnGroupPnl.add(jRadioButton2);

        sortCourseBtnGroup.add(jRadioButton3);
        jRadioButton3.setText("Khóa học online");
        jRadioButton3.setPreferredSize(new java.awt.Dimension(109, 30));
        sortCourseBtnGroupPnl.add(jRadioButton3);

        jPanel5.add(sortCourseBtnGroupPnl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tblCourse.getTableHeader().setFont(new Font("Segoe UI", 0, 14));
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        tblCourse.setFont(new Font("Segoe UI", 0, 14));
        leftRenderer.setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer)tblCourse.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        // Iterate over each column and set cell renderer and font
        for (int i = 0; i < tblCourse.getColumnCount(); i++) {
            tblCourse.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }
        tblCourse.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1045", "Calculus", "4", "Mathematics", null},
                {null, "1046", "Chemistry", "4", "Engineering", null},
                {null, "1061", "Physics", "4", "Enginerring", null},
                {null, "2042", "Literature", "4", "English", null},
                {null, "4022", "Microeconomics", "3", "Economics", null}
            },
            new String [] {
                "No.", "CourseID", "Title", "Credits", "Department Name", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourse.setRowHeight(35);
        tblCourse.getTableHeader().setReorderingAllowed(false);
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);
        if (tblCourse.getColumnModel().getColumnCount() > 0) {
            tblCourse.getColumnModel().getColumn(0).setMaxWidth(65);
            tblCourse.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        detailCoursePanel.setBackground(new java.awt.Color(255, 255, 255));
        detailCoursePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 206, 206)));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout15 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0);
        flowLayout15.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout15);

        txtCourseIDPnl.setBackground(new java.awt.Color(255, 255, 255));
        txtCourseIDPnl.setPreferredSize(new java.awt.Dimension(135, 50));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout3.setAlignOnBaseline(true);
        txtCourseIDPnl.setLayout(flowLayout3);

        jLabel16.setText("ID Khóa học:");
        jLabel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        jLabel16.setPreferredSize(new java.awt.Dimension(75, 45));
        txtCourseIDPnl.add(jLabel16);

        txtCourseID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCourseID.setFocusable(false);
        txtCourseID.setPreferredSize(new java.awt.Dimension(50, 40));
        txtCourseIDPnl.add(txtCourseID);

        jPanel1.add(txtCourseIDPnl);

        txtCourseNamePnl.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout4.setAlignOnBaseline(true);
        txtCourseNamePnl.setLayout(flowLayout4);

        jLabel17.setText("Tên khóa học:");
        jLabel17.setPreferredSize(new java.awt.Dimension(75, 40));
        txtCourseNamePnl.add(jLabel17);

        txtTitle.setPreferredSize(new java.awt.Dimension(205, 40));
        txtCourseNamePnl.add(txtTitle);

        jPanel1.add(txtCourseNamePnl);

        txtDepartmentPnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setText("Tên Khoa:");
        jLabel19.setPreferredSize(new java.awt.Dimension(55, 45));
        txtDepartmentPnl.add(jLabel19);

        cbDepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 206, 206)));
        cbDepartment.setPreferredSize(new java.awt.Dimension(150, 40));
        txtDepartmentPnl.add(cbDepartment);

        jPanel1.add(txtDepartmentPnl);

        txtCreditPnl.setBackground(new java.awt.Color(255, 255, 255));
        txtCreditPnl.setPreferredSize(new java.awt.Dimension(140, 55));
        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout5.setAlignOnBaseline(true);
        txtCreditPnl.setLayout(flowLayout5);

        jLabel18.setText("Tín chỉ:");
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 45));
        txtCreditPnl.add(jLabel18);

        txtCredit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCredit.setPreferredSize(new java.awt.Dimension(90, 40));
        txtCreditPnl.add(txtCredit);

        jPanel1.add(txtCreditPnl);

        txtDetailCourse.setBackground(new java.awt.Color(255, 255, 255));
        txtDetailCourse.setPreferredSize(new java.awt.Dimension(850, 220));
        java.awt.FlowLayout flowLayout13 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5);
        flowLayout13.setAlignOnBaseline(true);
        txtDetailCourse.setLayout(flowLayout13);

        txtLocationPnl.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout7.setAlignOnBaseline(true);
        txtLocationPnl.setLayout(flowLayout7);

        jLabel20.setText("Địa chỉ:");
        jLabel20.setPreferredSize(new java.awt.Dimension(70, 40));
        txtLocationPnl.add(jLabel20);

        txtLocation.setPreferredSize(new java.awt.Dimension(200, 40));
        txtLocationPnl.add(txtLocation);

        txtDetailCourse.add(txtLocationPnl);

        txtUrlPnl.setBackground(new java.awt.Color(255, 255, 255));
        txtUrlPnl.setPreferredSize(new java.awt.Dimension(300, 50));
        java.awt.FlowLayout flowLayout8 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout8.setAlignOnBaseline(true);
        txtUrlPnl.setLayout(flowLayout8);

        jLabel23.setText("URL:");
        jLabel23.setPreferredSize(new java.awt.Dimension(25, 40));
        txtUrlPnl.add(jLabel23);

        txtUrl.setMargin(new java.awt.Insets(2, 15, 2, 6));
        txtUrl.setPreferredSize(new java.awt.Dimension(255, 40));
        txtUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrlActionPerformed(evt);
            }
        });
        txtUrlPnl.add(txtUrl);

        txtDetailCourse.add(txtUrlPnl);

        txtTimePnl.setBackground(new java.awt.Color(255, 255, 255));
        txtTimePnl.setPreferredSize(new java.awt.Dimension(200, 50));
        java.awt.FlowLayout flowLayout12 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout12.setAlignOnBaseline(true);
        txtTimePnl.setLayout(flowLayout12);

        jLabel22.setText("Thời gian:");
        jLabel22.setPreferredSize(new java.awt.Dimension(60, 40));
        txtTimePnl.add(jLabel22);

        tpTime.setPreferredSize(new java.awt.Dimension(120, 40));
        txtTimePnl.add(tpTime);

        txtDetailCourse.add(txtTimePnl);

        txtDatePnl.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout11 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout11.setAlignOnBaseline(true);
        txtDatePnl.setLayout(flowLayout11);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Ngày:");
        jLabel21.setToolTipText("");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel21.setPreferredSize(new java.awt.Dimension(70, 40));
        txtDatePnl.add(jLabel21);

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 206, 206)));
        jPanel33.setPreferredSize(new java.awt.Dimension(500, 40));
        java.awt.FlowLayout flowLayout9 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout9.setAlignOnBaseline(true);
        jPanel33.setLayout(flowLayout9);

        txtMonday.setText("Thứ 2");
        txtMonday.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        txtMonday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMonday.setPreferredSize(new java.awt.Dimension(75, 30));
        jPanel33.add(txtMonday);

        txtTuesday.setText("Thứ 3");
        txtTuesday.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        txtTuesday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTuesday.setPreferredSize(new java.awt.Dimension(75, 30));
        jPanel33.add(txtTuesday);

        txtWednesday.setText("Thứ 4");
        txtWednesday.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        txtWednesday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtWednesday.setPreferredSize(new java.awt.Dimension(75, 30));
        jPanel33.add(txtWednesday);

        txtThursday.setText("Thứ 5");
        txtThursday.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        txtThursday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtThursday.setPreferredSize(new java.awt.Dimension(75, 30));
        jPanel33.add(txtThursday);

        txtFriday.setText("Thứ 6");
        txtFriday.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        txtFriday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtFriday.setPreferredSize(new java.awt.Dimension(75, 30));
        jPanel33.add(txtFriday);

        txtSaturday.setText("Thứ 7");
        txtSaturday.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 15));
        txtSaturday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSaturday.setPreferredSize(new java.awt.Dimension(75, 30));
        jPanel33.add(txtSaturday);

        txtDatePnl.add(jPanel33);

        txtDetailCourse.add(txtDatePnl);

        jLabel2.setText("Loại:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 14, 0, 0));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 40));
        txtDetailCourse.add(jLabel2);

        txtType.setFocusable(false);
        txtType.setPreferredSize(new java.awt.Dimension(140, 40));
        txtDetailCourse.add(txtType);

        jPanel1.add(txtDetailCourse);

        buttonPnl.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout10 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT);
        flowLayout10.setAlignOnBaseline(true);
        buttonPnl.setLayout(flowLayout10);

        btnCancel.setText("Đóng");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 206, 206)));
        btnCancel.setPreferredSize(new java.awt.Dimension(112, 40));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        buttonPnl.add(btnCancel);

        btnSave.setText("Lưu");
        btnSave.setBackground(new java.awt.Color(56, 122, 223));
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 196, 237)));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setPreferredSize(new java.awt.Dimension(112, 40));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        buttonPnl.add(btnSave);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout detailCoursePanelLayout = new javax.swing.GroupLayout(detailCoursePanel);
        detailCoursePanel.setLayout(detailCoursePanelLayout);
        detailCoursePanelLayout.setHorizontalGroup(
            detailCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        detailCoursePanelLayout.setVerticalGroup(
            detailCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(detailCoursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailCoursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchOnsiteCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOnsiteCourseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchOnsiteCourseBtnActionPerformed

    private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed
        courseAddForm.setVisible(true);
        courseAddForm.getOnsiteInformationCourse().setVisible(false);
    }//GEN-LAST:event_addCourseBtnActionPerformed

    private void editCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseBtnActionPerformed
        detailCoursePanel.setVisible(true);
    }//GEN-LAST:event_editCourseBtnActionPerformed

    private void deleteCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseBtnActionPerformed
        int deleteChoice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa dòng này không?");
    }//GEN-LAST:event_deleteCourseBtnActionPerformed

    private void selectCourse() {
        int row = tblCourse.getSelectedRow();
        int colsCount = tblCourse.getColumnCount();

        // get value course from table
        String courseID = tblCourse.getValueAt(row, 1).toString();
        int ID = Integer.parseInt(courseID);
        String title = tblCourse.getValueAt(row, 2).toString();
        String credits = tblCourse.getValueAt(row, 3).toString();
        String deparment = tblCourse.getValueAt(row, 4).toString();

        // set value to text field
        txtCourseID.setText(courseID);
        txtTitle.setText(title);
        txtCredit.setText(credits);
        cbDepartment.setSelectedItem(deparment);

        String type = tblCourse.getValueAt(row, colsCount - 1).toString(); // get value course_type in last cell of row
        txtType.setText(type);
        switch (type)
        {
            case "Online" ->
            {
                // hide panel of onsite course
                txtLocationPnl.setVisible(false);
                txtDatePnl.setVisible(false);
                txtTimePnl.setVisible(false);

                // show panel of online course
                txtUrlPnl.setVisible(true);

                // get data of online course
                OnlineCourseDTO onlCourse = onlineCourseBLL.selectByID(ID);
                String url = onlCourse.getUrl();

                // set data to text field
                txtUrl.setText(url);
            }
            case "Onsite" ->
            {
                // show panel of onsite course
                txtLocationPnl.setVisible(true);
                txtDatePnl.setVisible(true);
                txtTimePnl.setVisible(true);

                // hide panel of online course
                txtUrlPnl.setVisible(false);

                // get data of online course
                OnsiteCourseDTO onsCourse = onsiteCourseBLL.selectByID(ID);
                String location = onsCourse.getLocation();
                String days = onsCourse.getDays();
                Time time = onsCourse.getTime();
                LocalTime localtime = LocalTime.parse(String.valueOf(time));

                // set data to text field
                txtLocation.setText(location);
                tpTime.setTime(localtime);
                tpTime.requestFocus(false);
                while (!days.isEmpty())
                {
                    char dayChar = days.charAt(days.length() - 1);
                    String day = String.valueOf(dayChar);
                    switch (day)
                    {
                        case "M":
                            txtMonday.setSelected(true);
                            break;
                        case "T":
                            txtTuesday.setSelected(true);
                            break;
                        case "W":
                            txtWednesday.setSelected(true);
                            break;
                        case "H":
                            txtThursday.setSelected(true);
                            break;
                        case "F":
                            txtFriday.setSelected(true);
                            break;
                        case "S":
                            txtSaturday.setSelected(true);
                            break;
                        default:
                            throw new AssertionError();
                    }

                    days = days.substring(0, days.length() - 1);
                }

            }
            default ->
                throw new AssertionError();
        }
    }

    private void clearText() {
        txtCourseID.setText("");
        txtTitle.setText("");
        txtCredit.setText("");
        cbDepartment.getEditor().setItem("");
        txtLocation.setText("");
        tpTime.setText("");

        txtMonday.setSelected(false);
        txtTuesday.setSelected(false);
        txtWednesday.setSelected(false);
        txtThursday.setSelected(false);
        txtFriday.setSelected(false);
        txtSaturday.setSelected(false);
    }

    private void displayErrorMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void displayMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Information", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        detailCoursePanel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String courseIDstr = txtCourseID.getText();
        if (courseIDstr.isBlank())
        {
            displayErrorMessage("Chưa chọn khóa học cần sửa");
            return;
        }
        boolean success = false;
        String title = txtTitle.getText();
        int courseID = Integer.parseInt(courseIDstr);
        int departmentIndex = cbDepartment.getSelectedIndex();
        int departmentID = listDepartment.get(departmentIndex).getDepartmentID();
        int credits = Integer.parseInt(txtCredit.getText());
        CourseDTO course = new CourseDTO(courseID, departmentID, credits, title);
        success = courseBLL.updateCourse(course);
        String course_type = txtType.getText();
        switch (course_type)
        {
            case "Online" ->
            {
                String url = txtUrl.getText();
                OnlineCourseDTO onlineCourse = new OnlineCourseDTO(url, courseID, departmentID, credits, title);
                success = onlineCourseBLL.updateOnlineCourse(onlineCourse);
            }
            case "Onsite" ->
            {
                String location = txtLocation.getText();
                LocalTime localtime = tpTime.getTime();
                Time time = Time.valueOf(localtime);
                String Days = "";
                if (txtMonday.isSelected())
                {
                    Days += "M";
                }
                if (txtTuesday.isSelected())
                {
                    Days += "T";
                }
                if (txtWednesday.isSelected())
                {
                    Days += "W";
                }
                if (txtThursday.isSelected())
                {
                    Days += "H";
                }
                if (txtFriday.isSelected())
                {
                    Days += "F";
                }
                if (txtSaturday.isSelected())
                {
                    Days += "S";
                }

//                System.out.println(location + " - " + Days + " - " + time);
                OnsiteCourseDTO onsiteCourse = new OnsiteCourseDTO(location, Days, time, courseID, departmentID, credits, title);
                success = onsiteCourseBLL.updateOnsiteCourse(onsiteCourse);
            }
            default ->
                throw new AssertionError();
        }
        if (success)
        {
            loadData();
            ((AbstractTableModel) tblCourse.getModel()).fireTableDataChanged();
            clearText();
            displayMessage("Update Course Successfully!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
        clearText();
        selectCourse();
    }//GEN-LAST:event_tblCourseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseBtn;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel buttonPnl;
    private javax.swing.JComboBox<String> cbDepartment;
    private javax.swing.JButton deleteCourseBtn;
    private javax.swing.JPanel detailCoursePanel;
    private javax.swing.JButton editCourseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton searchOnsiteCourseBtn;
    private javax.swing.JTextField searchOnsiteCourseValue;
    private javax.swing.ButtonGroup sortCourseBtnGroup;
    private javax.swing.JPanel sortCourseBtnGroupPnl;
    private javax.swing.JTable tblCourse;
    private com.github.lgooddatepicker.components.TimePicker tpTime;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JPanel txtCourseIDPnl;
    private javax.swing.JPanel txtCourseNamePnl;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JPanel txtCreditPnl;
    private javax.swing.JPanel txtDatePnl;
    private javax.swing.JPanel txtDepartmentPnl;
    private javax.swing.JPanel txtDetailCourse;
    private javax.swing.JCheckBox txtFriday;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JPanel txtLocationPnl;
    private javax.swing.JCheckBox txtMonday;
    private javax.swing.JCheckBox txtSaturday;
    private javax.swing.JCheckBox txtThursday;
    private javax.swing.JPanel txtTimePnl;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JCheckBox txtTuesday;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JPanel txtUrlPnl;
    private javax.swing.JCheckBox txtWednesday;
    // End of variables declaration//GEN-END:variables
}
